# Generated by Django 2.0.4 on 2018-07-03 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mpttcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 4, 51, 46, 19610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 3, 4, 51, 46, 20609, tzinfo=utc)),
        ),
    ]
