# Generated by Django 2.0.4 on 2018-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, max_length=500, verbose_name='昵称'),
        ),
    ]
